name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    tags:
      - v*
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          args: --timeout=500s
      - name: Test
        run: make test
